#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 17 21:08:07 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Shader.zip
