param(
    [string]$SoundsRoot = "$PSScriptRoot\..\resourcepack\source\assets\marallyzen\sounds",
    [string]$OutputFile = "$PSScriptRoot\..\plugins\Denizen\story\audio.generated.yml"
)

$ErrorActionPreference = 'Stop'
$ffprobe = Get-Command ffprobe -ErrorAction Stop
$resolvedRoot = (Resolve-Path -LiteralPath $SoundsRoot).Path
$records = [System.Collections.Generic.List[object]]::new()
$usedIds = @{}

Get-ChildItem -LiteralPath $resolvedRoot -Recurse -Filter '*.ogg' | Sort-Object FullName | ForEach-Object {
    $relative = [IO.Path]::GetRelativePath($resolvedRoot, $_.FullName).Replace('\', '/')
    $id = [IO.Path]::GetFileNameWithoutExtension($_.Name).ToLowerInvariant()
    if ($usedIds.ContainsKey($id)) {
        throw "Duplicate audio ID '$id': '$relative' and '$($usedIds[$id])'. Rename one file."
    }
    $usedIds[$id] = $relative
    $secondsText = & $ffprobe.Source -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -- $_.FullName
    $seconds = [double]::Parse($secondsText.Trim(), [Globalization.CultureInfo]::InvariantCulture)
    $ticks = [Math]::Max(1, [Math]::Ceiling($seconds * 20.0))
    $soundPath = [IO.Path]::ChangeExtension($relative, $null).Replace('\', '/')
    $records.Add([pscustomobject]@{ Id = $id; Sound = "marallyzen:$soundPath"; Ticks = $ticks })
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Generated by tools/build_story_audio_manifest.ps1')
$lines.Add('audio:')
foreach ($record in $records) {
    $lines.Add("  $($record.Id):")
    $lines.Add("    sound_id: $($record.Sound)")
    $lines.Add("    duration: $($record.Ticks)t")
}

$outputDirectory = Split-Path -Parent $OutputFile
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
[IO.File]::WriteAllLines($OutputFile, $lines, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $($records.Count) audio entries: $OutputFile"
