entity.20002 = minecraft:text_display
entity.20003 = minecraft:name_tag
entity.100 = minecraft:piglin minecraft:piglin_brute minecraft:zombified_piglin
entity.101 = minecraft:ghast
entity.102 = minecraft:stray
entity.103 = minecraft:bogged
entity.104 = minecraft:breeze
entity.105 = minecraft:blaze
entity.106 = minecraft:vex
entity.107 = minecraft:endermite
entity.108 = minecraft:guardian minecraft:elder_guardian
entity.109 = minecraft:end_crystal
entity.110 = minecraft:entity_flame
