item.10020 = torch lantern campfire jack_o_lantern
item.10021 = soul_torch soul_lantern soul_campfire
item.10022 = flint_and_steel fire_charge
item.10023 = glowstone
item.10024 = sea_lantern beacon
item.10025 = shroomlight
item.10026 = redstone_lamp
item.10027 = ochre_froglight
item.10028 = verdant_froglight
item.10029 = pearlescent_froglight
item.10031 = end_rod
item.10034 = glow_lichen
item.10038 = redstone_torch
item.10039 = lava_bucket
item.10043 = soul_torch soul_lantern
item.10044 = beacon
item.10047 = crying_obsidian
item.10050 = candle
item.10051 = ochre_froglight
item.10052 = verdant_froglight
item.10053 = pearlescent_froglight
item.10054 = enchanting_table
item.10055 = amethyst_cluster
item.10058 = redstone_block
item.10087 = copper_torch copper_lantern
